[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200

# Monad Testnet
eth-rpc-url = "https://testnet-rpc.monad.xyz"
chain_id = 10143

# Verification
metadata = true
metadata_hash = "none"
use_literal_content = true

[profile.mainnet]
eth-rpc-url = "https://rpc.monad.xyz"
chain_id = 143
